apiVersion: batch/v1
kind: Job
metadata:
  name: install-crds
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl create namespace ambassador
              kubectl apply -f https://app.getambassador.io/yaml/edge-stack/3.12.1/aes-crds.yaml
              kubectl wait --timeout=90s --for=condition=available deployment emissary-apiext -n emissary-system
      restartPolicy: OnFailure
