export const REQUEST_START = 'REQUEST_START';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const SET_OPEN_WINDOW = 'SET_OPEN_WINDOW';
export const APP_LOADED = 'APP_LOADED';
export const RESET_APP_ERROR = 'RESET_APP_ERROR';
