import { AppNav } from '@pokehub/frontend/pokehub-nav-components';
import { QueryProvider } from '@pokehub/frontend/shared-query-client-provider';

import { AppBootstrapper } from './bootstrapper';
import './global.css';

export const metadata = {
  title: 'Welcome to pokehub-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="h-screen">
        <AppBootstrapper>
          <QueryProvider>
            <AppNav />
            {children}
          </QueryProvider>
        </AppBootstrapper>
      </body>
    </html>
  );
}
