import { AppBootstrapper } from './(components)/bootstrapper';
import './global.css';

//import { createFetchClient } from '@pokehub/frontend/shared-data-provider';

export const metadata = {
  title: 'Welcome to pokehub-app',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppBootstrapper>{children}</AppBootstrapper>
      </body>
    </html>
  );
}
