export const CHAT_OPENED = 'CHAT_OPENED';
export const CHAT_CLOSED = 'CHAT_CLOSED';
export const GET_CHAT_ROOMS_SUCCESS = 'GET_CHAT_ROOMS_SUCCESS';
export const CHATROOM_MESSAGE_RECEIVED = 'CHATROOM_MESSAGE_RECEIVED';
export const CHATROOM_MESSAGE_SENT = 'CHATROOM_MESSAGE_SENT';
export const SET_CHATROOM_STATE = 'SET_CHATROOM_STATE';
export const LOAD_CHATROOM_CONVERSATION = 'LOAD_CHATROOM_CONVERSATION';

export const SET_DM_ACTIVE = 'SET_DM_ACTIVE';
export const SET_DM_INACTIVE = 'SET_DM_INACTIVE';
export const OPEN_DM = 'OPEN_DM';
export const CLOSE_DM = 'CLOSE_DM';
export const LOAD_DM_CONVERSATION = 'LOAD_DM_CONVERSATION';
export const DM_SENT = 'DM_SENT';
export const RESET_DM_UNREAD_MESSAGES = 'RESET_DM_UNREAD_MESSAGES';
export const CLOSE_ALL_DMS = 'CLOSE_ALL_DMS';
export const DM_RECEIVED = 'DM_RECEIVED';