---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: samplehost
  namespace: ambassador
spec:
  hostname: internal.pokehub.ml
  acmeProvider:
    authority: none
  tlsSecret:
    name: tls-cert
  requestPolicy:
    insecure:
      action: Route
