apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: mmumshad/simple-webapp
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: webapp
  type: ClusterIP
