---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  namespace: monitoring
  name: grafana
spec:
  hostname: "*"
  prefix: /grafana/
    #rewrite: /grafana
  service: grafana:80
  tls: istio-upstream

