apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: postgres
  name: postgresql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
