---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: main-host
  namespace: emissary
spec:
  hostname: pokehub.ml
  acmeProvider:
    authority: none
  tlsSecret:
    name: ambassador-certs
  requestPolicy:
    insecure:
      action: Route
