---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: internaldomain
  namespace: ambassador
spec:
  hostname: internal.pokehub.ml
  acmeProvider:
    authority: none
  tlsSecret:
    name: tls-cert-internal
  requestPolicy:
    insecure:
      action: Route
